build_outbox_cdk_context() {
  local target_outbox_desired_count="$1"
  cdk_context=(
    -c "envName=${deploy_env}"
    -c "gatewayUseNatGateway=${use_nat_gateway}"
    -c "gatewayRedisNodeType=${redis_node_type}"
    -c "authJwtAlgorithm=${auth_jwt_algorithm}"
    -c "gatewayDesiredCount=${gateway_desired_count}"
    -c "gatewayImageTag=${gateway_image_tag}"
    -c "authDesiredCount=${auth_desired_count}"
    -c "authImageTag=${auth_image_tag}"
    -c "tenantDesiredCount=${tenant_desired_count}"
    -c "tenantImageTag=${tenant_image_tag}"
    -c "adminBffDesiredCount=${admin_bff_desired_count}"
    -c "adminBffImageTag=${admin_bff_image_tag}"
    -c "auditDesiredCount=${audit_desired_count}"
    -c "auditImageTag=${audit_image_tag}"
    -c "outboxDesiredCount=${target_outbox_desired_count}"
    -c "outboxImageTag=${outbox_image_tag}"
    -c "outboxSources=${outbox_sources}"
    -c "outboxWorkerEnabled=${outbox_worker_enabled}"
    -c "outboxPublisherType=${outbox_publisher_type}"
  )

  append_context() {
    local key="$1"
    local value="$2"
    if [[ -n "${value}" ]]; then
      cdk_context+=(-c "${key}=${value}")
    fi
  }

  append_context "gatewayAcmCertificateArn" "${GATEWAY_ACM_CERTIFICATE_ARN_INPUT}"
  append_context "gatewayDomainName" "${GATEWAY_DOMAIN_NAME_INPUT}"
  append_context "gatewayCorsAllowedOrigins" "${GATEWAY_CORS_ALLOWED_ORIGINS_INPUT}"
  append_context "gatewayJwtSecretArn" "${GATEWAY_JWT_SECRET_ARN_INPUT}"
  append_context "authCorsAllowedOrigins" "${AUTH_CORS_ALLOWED_ORIGINS_INPUT}"
  append_context "authDatabaseUrlSecretArn" "${AUTH_DATABASE_URL_SECRET_ARN_INPUT}"
  append_context "authJwtSecretArn" "${AUTH_JWT_SECRET_ARN_INPUT}"
  append_context "authJwtPrivateKeySecretArn" "${AUTH_JWT_PRIVATE_KEY_SECRET_ARN_INPUT}"
  append_context "authJwtPublicKeySecretArn" "${AUTH_JWT_PUBLIC_KEY_SECRET_ARN_INPUT}"
  append_context "authInternalAuthSecretArn" "${AUTH_INTERNAL_AUTH_SECRET_ARN_INPUT}"
  append_context "tenantCorsAllowedOrigins" "${TENANT_CORS_ALLOWED_ORIGINS_INPUT}"
  append_context "tenantDatabaseUrlSecretArn" "${TENANT_DATABASE_URL_SECRET_ARN_INPUT}"
  append_context "tenantInternalAuthSecretArn" "${TENANT_INTERNAL_AUTH_SECRET_ARN_INPUT}"
  append_context "adminBffCorsAllowedOrigins" "${ADMIN_BFF_CORS_ALLOWED_ORIGINS_INPUT}"
  append_context "adminBffAuthInternalAuthSecretArn" "${ADMIN_BFF_AUTH_INTERNAL_AUTH_SECRET_ARN_INPUT}"
  append_context "adminBffTenantInternalAuthSecretArn" "${ADMIN_BFF_TENANT_INTERNAL_AUTH_SECRET_ARN_INPUT}"
  append_context "adminBffAuditInternalAuthSecretArn" "${ADMIN_BFF_AUDIT_INTERNAL_AUTH_SECRET_ARN_INPUT}"
  append_context "auditCorsAllowedOrigins" "${AUDIT_CORS_ALLOWED_ORIGINS_INPUT}"
  append_context "auditDatabaseUrlSecretArn" "${AUDIT_DATABASE_URL_SECRET_ARN_INPUT}"
  append_context "auditInternalAuthSecretArn" "${AUDIT_INTERNAL_AUTH_SECRET_ARN_INPUT}"
  append_context "auditLogServiceUrl" "${AUDIT_LOG_SERVICE_URL_INPUT}"
  append_context "auditEventConsumerEnabled" "${AUDIT_EVENT_CONSUMER_ENABLED_INPUT}"
  append_context "auditEventQueueUrl" "${AUDIT_EVENT_QUEUE_URL_INPUT}"
  append_context "outboxCorsAllowedOrigins" "${OUTBOX_CORS_ALLOWED_ORIGINS_INPUT}"
  append_context "outboxEventBridgeBusName" "${OUTBOX_EVENTBRIDGE_BUS_NAME_INPUT}"
  append_context "outboxSqsQueueUrl" "${OUTBOX_SQS_QUEUE_URL_INPUT}"
  append_context "authIamOutboxDatabaseUrlSecretArn" "${AUTH_IAM_OUTBOX_DATABASE_URL_SECRET_ARN_INPUT}"
  append_context "tenantOutboxDatabaseUrlSecretArn" "${TENANT_OUTBOX_DATABASE_URL_SECRET_ARN_INPUT}"
  append_context "wmsOutboxDatabaseUrlSecretArn" "${WMS_OUTBOX_DATABASE_URL_SECRET_ARN_INPUT}"
  append_context "authIamServiceUrl" "${AUTH_IAM_SERVICE_URL_INPUT}"
  append_context "adminBffServiceUrl" "${ADMIN_BFF_SERVICE_URL_INPUT}"
  append_context "tenantServiceUrl" "${TENANT_SERVICE_URL_INPUT}"
}
