FROM node:22-alpine AS base
WORKDIR /app
RUN corepack enable

FROM base AS deps
COPY package.json pnpm-lock.yaml* pnpm-workspace.yaml ./
COPY apps ./apps
COPY packages ./packages
RUN pnpm install --frozen-lockfile

FROM deps AS build
ARG APP_NAME
RUN pnpm --filter ${APP_NAME} build

FROM nginx:1.27-alpine AS runner
COPY --from=build /app/apps/${APP_NAME}/dist /usr/share/nginx/html
